name: Flutter CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Dart SDK
      uses: dart-lang/setup-dart@v1.2
      with:
        sdk: '>=3.4.3 <4.0.0'  # Specify the Dart SDK version range here

    - name: Install dependencies
      run: dart pub get

    - name: Run tests
      run: dart test